### ISSUE TITLE
Purchase waterproofing materials

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/Society-materials#30]
We need to buy some waterproofing materials, I would propose plasti dip and silicone:
https://www.amazon.co.uk/Plasti-Dip-Plastic-Rubber-Paint/dp/B0114Z42F8/ref=sr_1_7?ie=UTF8&qid=1468225472&sr=8-7&keywords=plasti+dip 

https://www.amazon.co.uk/Everbuild-EVBGPSESQCL-General-Purpose-Silicone/dp/B001V9NANS/ref=sr_1_10?ie=UTF8&qid=1468225658&sr=8-10&keywords=silicone 

Plasti dip is for covering entire parts, silicone for more selective work.
It is probably better to buy several smaller packages of silicone since they will be easier to apply.
Any other opinions?

**Comment by smaria** [comment]
We probably also need something to waterproof the servos that will allow them to keep moving - some sort of oil?

**Comment by Nanoseb** [comment]
I thought we already bought some marine grease to waterproof servos.

**Comment by smaria** [comment]
that is correct, I saw that in our purchase list just ten minutes before writing this ticket... thanks
